In [1]:
import torch
torch.cuda.empty_cache()
from cocoonclassifier_class import MODEL
# import importlib
# importlib.reload(MODEL)
loss = "CE"
optimizer = "AdamW"
with torch.no_grad():
    cocoon = MODEL('resnet', 50, 16, 'finetune', loss, optimizer)
    cocoon.read_model('./models/finetune/resnet/bs_16_resnet_op_AdamW_ls_CE')
cocoon.read_test_data("D:/Desktop/莊詠竣/ml/data/after_aug/delta_day_3__train_test_mix/val", 2)
accuracy, recall, precision, f1_score = cocoon.test(predict=True)


c:\Users\s47vd\miniconda3\envs\lacewing\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
c:\Users\s47vd\miniconda3\envs\lacewing\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.

tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 1])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 1])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([1, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0, 0])
tensor([0,

KeyboardInterrupt: 

In [2]:

    print(path)

d:\Desktop\莊詠竣\transplant_system\transplant_system\transferlearning
c:\Users\h\anaconda3\envs\lacewing\python39.zip
c:\Users\h\anaconda3\envs\lacewing\DLLs
c:\Users\h\anaconda3\envs\lacewing\lib
c:\Users\h\anaconda3\envs\lacewing

c:\Users\h\anaconda3\envs\lacewing\lib\site-packages
c:\Users\h\anaconda3\envs\lacewing\lib\site-packages\win32
c:\Users\h\anaconda3\envs\lacewing\lib\site-packages\win32\lib
c:\Users\h\anaconda3\envs\lacewing\lib\site-packages\Pythonwin
